# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: "http://www.thesoapcollective.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
title: The Soap Collective
description: "The Soap Collective is a next-generation creative agency. Using the latest immersive technology, we build elevated storytelling experiences for brands and consumers."
email: info@thesoapcollective.com
phone: 1.720.729.7627
address: "San Francisco, CA"
map_url: "https://www.google.com/maps/place/San+Francisco,+CA/@37.757815,-122.5076401,12z"
reel_url: https://www.youtube.com/watch?v=nIYHl-brGOE
blog_url: https://blog.thesoapcollective.com
twitter_username: soapcollective
google_analytics_id: UA-11359166-1
typekit_id: dhn8nfe

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
